eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8096
spring:
  application:
    name: service-feign
    # 数据库链接
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.31.204:3306/ceshiedu
      username: root
      password: root

    thymeleaf:
      cache: false
      content-type: text/html
      mode: LEGACYHTML5
      prefix: classpath:/templates/
      suffix: .html

    redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 192.168.31.16
      # Redis服务器连接端口
      port: 7001
      # Redis 密码
      password: 123456
      jedis:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 8
          # 连接池中的最大空闲连接
          max-idle: 500
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 2000
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 10000
      # 连接超时时间（毫秒）
      timeout: 2000

constants:
  # QQ
  qqAppId: 101514490
  qqAppSecret: 01df0231020ee43144d8a104bb77611a
  qqRedirectUrl: http://localhost:8096/money/callback
