eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8095
spring:
  application:
    name: service-feign
    # 数据库链接
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    servlet:
      content-type: text/html




